# Generated by Django 3.1 on 2020-08-13 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_forgottokens_usermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgottokens',
            options={'verbose_name': 'ForgotToken'},
        ),
        migrations.AlterField(
            model_name='forgottokens',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
